### ISSUE TITLE
Make not working

### ISSUE THREAD

**Issue by carlottafabris** [cmaumet/fsl#6]
Hi! I am trying to run the commands I found in the Make section of the README, but I am getting this error: cd: /usr/local/fsl_MODIFIED/src/cluster: No such File or directory

Am I doing something wrong?

Thank you,
Carlotta.

**Comment by LukeYao2018** [comment]
Hi, I have the same question with Carlottafabris 
the error happened when I typed the READ, like this,
-bash: cd: /usr/local/fsl_MODIFIED/src/cluster: No such file or directory

Any solutions will be very appreciated
Thank you
Shun

**Comment by carlottafabris** [comment]
Hi!

Here is how I solved it:
1) mkdir ~/fsl_modified
cp -r /path/to/your/FSL ~/fsl_modified

2) Replace the /path/to/your/FSL with your install path, of course.

Tell me if you have any other problem with this.

Il giorno dom 10 mar 2019 alle ore 07:04 LukeYao2018 <
notifications@github.com> ha scritto:

**Comment by cmaumet** [comment]
Hi both,

Thanks for your interest in this code! This extension for voxelwise thresholding is now native in FSL as of version 5.0.10. This repository is no longer maintained. I will update the README to include that info.
