### ISSUE TITLE
Updated Cluster Tool Inquiry

### ISSUE THREAD

**Issue by kvandeloo97** [cmaumet/fsl#7]
Hi there,

I am wondering how one is to determine which thresholding values to use i.e. for the -i flag. I am also wondering about values for the -d and -r flag. I am attempting to extract information about specific WM tracts, i.e. the ATR, ILF, SLF, cingulum bundle, ALIC, UNC and IFO under the JHU white matter atlas using this script. Thanks so much.

Katie

**Comment by cmaumet** [comment]
Hi @kvandeloo97,

This extension for voxel-wise thresholding is now natively part of FSL (as of version 5.0.10). This repository is therefore no longer maintained. I would recommend that you use the native version in FSL and reach out to the FSL mailing list for your questions.

Best, Camille
